import StyledComponentsRegistry from './registry';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StyledComponentsRegistry>
      <html lang="pt-br">
        <body style={{margin:0}}>{children}</body>
      </html>
    </StyledComponentsRegistry>
  )
}
