import gado from "./Foto_Gado_Central.svg";
import logo from './Logo.svg'
import logo2 from './Logo2.svg'
import fundoLogin from './fundoLogin.svg'
import touros from './touros.svg'
import fundo2 from './Fundo 2.svg'
import vaca from './vaca.svg'
import logoBranca from './LogoBranca.svg'
import logo2Branca from './Logo2Branca.svg'
import social from './social-prove.svg'
import cartao from './cartao.svg'
import pix from './pix.svg'
import card from './card.svg'
import boleto from './boleto.png'
import Home from './Home.svg'
import animal from './animal.svg'
import comunic from './comunic.svg'
import user from './user.svg'
import animalBlue from './animalBlue.svg'
import done from './done.svg'
import waiting from './waiting.svg'
import arrowLeft from './Shape.svg'
import hamb from './hamburguer.svg'
import search from './search.svg'
import seta from './seta.svg'
import boi from './boiExample.svg'
import add from './add.svg'
import group from './group.svg'

export {group,add,boi,seta,search,hamb, arrowLeft, done,waiting,animalBlue,user, Home,animal,comunic,boleto,card,pix, cartao, social,gado, logo, logo2, fundoLogin,touros,fundo2, vaca, logoBranca, logo2Branca}